name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-linux-riscv:
    name: Build (Linux-RV)
    runs-on: ubuntu-latest
    # Tighten permissions granted to the GITHUB_TOKEN
    permissions:
      packages: write # for uraimo/run-on-arch-action to cache docker images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cross-Compile Support on Ubuntu
        uses: cyberjunk/gha-ubuntu-cross@v4
        with:
          arch: riscv64
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install gperf desktop-file-utils
          pip install meson ninja
      - name: Install cross dependencies
        run: |
          sudo apt-get -y install libgtk-4-dev:riscv64 libjudy-dev:riscv64 libgirepository1.0-dev:riscv64
      - name: Setup meson build
        run: meson setup buildCross --cross-file=.github/workflows/riscv64-linux-gnu.txt
      - name: Compile GTKWave
        run: meson compile -C buildCross
